config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  root "administrators#index" 

  get '/login', to: 'login#index'
  post '/login', to: 'login#logar'
  get '/logout', to: 'login#logout'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :email, format: {
    with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  }
  validates :name, :email, :password, presence: true
  validates :email, uniqueness: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  before_action :set_administrator, only: %i[ show edit update destroy ]

  # GET /administrators or /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1 or /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators or /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
        format.html { redirect_to administrators_path, notice: "Adicionado novo usuário." }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1 or /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to administrators_path, notice: "Alterado com sucesso." }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1 or /administrators/1.json
  def destroy
    @administrator.destroy

    respond_to do |format|
      format.html { redirect_to administrators_url, notice: "Administrator was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def administrator_params
      params.require(:administrator).permit(:name, :email, :password)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action  :authenticate_user!

  def authenticate_user!
    return if request.path_parameters[:format] == 'json'

    if cookies[:home_adm].blank?
      redirect_to "/login"
    end
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
    skip_before_action :authenticate_user!
    def index;end


  def logar
    user = Administrator.where(email: params["login"]["email"], password: params["login"]["password"])
    if user.present?
      time = params["login"]["lembrar"] == "1" ? 1.year.from_now : 30.minutes.from_now
      user = user.first
      value = {
        id: user.id,
        nome: user.name,
        email: user.email
      }
      cookies[:home_adm] = { value: value.to_json, expires: time, httponly: true }

      redirect_to root_path
    else
      flash[:erro] = "Email ou senha inválidos"
      redirect_to login_path
    end
  end

  def logout
    cookies[:home_adm] = nil
    redirect_to login_path
  end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/administrators/_administrator.html.erb
<div id="<%= dom_id administrator %>">
  <tr>
    <td><%= administrator.name %></td>
    <td><%= administrator.email %></td>
    <td> <%= administrator.password %></td>
    <td><%= link_to "Detalhes", administrator, class: "btn-default" %></td>
  </tr>
</div>

app/views/administrators/_form.html.erb
<div class="box-content-modal">

  <%= form_with(model: administrator) do |form| %>
  <% if administrator.errors.any? %>
      <div style="color: red">
        <%= pluralize(administrator.errors.count, "error") %> prohibited this administrator from being saved:
        <ul>
          <% administrator.errors.each do |error| %>
          <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-component">
      <%= form.label :name, style: "display: block" %>
      <div class="form-input">
        <%= form.text_field :name %>
      </div>
    </div>
    <div class="form-component">
      <%= form.label :email, style: "display: block" %>
      <div class="form-input">
        <%= form.text_field :email %>
      </div>
    </div>
    <div class="form-component">
      <%= form.label :password, style: "display: block" %>
      <div class="form-input">
       <%= form.text_field :password %>
      </div>
    </div>
    <div class="box-link">
      <%= form.submit :salvar, class: "btn-default" %>
<% end %>
      <%= button_to "Cancelar", @administrator,method: :get, class: "btn-default" %>
    </div>
</div>

app/views/administrators/edit.html.erb
<div class="box-content">
  <div class="box-controller">
    <div class="box-controller-title">
      <h1>Editar</h1>
    </div>
    <div>
      <%= link_to "home", administrators_path, class: "btn-default" %>
      <%= link_to "Sair", logout_path, class: "btn-default" %>
    </div>
  </div>

  <%= render "form", administrator: @administrator %>

  <br>


</div>

app/views/administrators/index.html.erb
<div class="box-content">

  <p style="color: green"><%= notice %></p>
  
  <div class="box-controller">
    <div class="box-controller-title">
      <h1>Administrador</h1>
    </div>
    <div>
      <%= link_to "Novo", new_administrator_path, class: "btn-default" %>
      <%= link_to "Sair", logout_path, class: "btn-default" %>
    </div>
  </div>
    
  <div class="table-administrator">
    <table>
      <tr>
        <th>Nome</th>
        <th>Email</th>
        <th>Senha</th>
        <th>Ações</th>
      </tr>
    <% @administrators.each do |administrator| %>
    <%= render administrator %>
    <% end %>
  </table>
  </div>
</div>

app/views/administrators/new.html.erb
<div class="box-content">
  <div class="box-controller">
    <div class="box-controller-title">
      <h1>Novo</h1>
    </div>
    <div>
      <%= link_to "home", administrators_path, class: "btn-default" %>
      <%= link_to "Sair", logout_path, class: "btn-default" %>
    </div>
  </div>  

  <%= render "form", administrator: @administrator %>

</div>

app/views/administrators/show.html.erb
<div class="box-content">
  <div class="box-controller">
    <div class="box-controller-title">
      <h1><%= @administrator.name %></h1>
    </div>
    <div>
      <%= link_to "home", administrators_path, class: "btn-default" %>
      <%= link_to "Sair", logout_path, class: "btn-default" %>
    </div>
  </div>
<div class="box-content-modal">
  <p style="color: green"><%= notice %></p>
  <div>
    <%= @administrator.email %> <br>
    <%= @administrator.password %>
    <div class="box-link">
      <%= button_to "Editar", edit_administrator_path(@administrator),method: :get, class: "btn-default" %>
      <%= button_to "Excluir", @administrator, method: :delete, class: "btn-default" %>
    </div>
  </div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LoginRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<div class="box-login">
  <div class="error-default">
    <%= form_for("login") do |f| %>
    <% if flash[:erro].present? %>
    <%= flash[:erro] %>
    <% end %>
  </div>
  <div class="form-component">
    <%= f.label :email, 'Email', class: "col-sm-2 control-label" %>
    <div class="form-input">
      <%= f.text_field :email, class: "form-control" %><br>
    </div>
  </div>
  <div class="form-component">
    <%= f.label :password, 'Senha', class: "col-sm-2 control-label" %>
    <div class="form-input">
      <%= f.password_field :password, class: "form-control" %><br>
    </div>
  </div>
  <div class="form-component">
    <input type="checkbox" value="1" checked="checked" name="login[lembrar]" id="login_lembrar">
    <%= f.label :lembrar, 'Deixe me logado', class: "col-sm-2 control-label" %>
  </div>
  <div class="form-btn">
    <%= f.submit 'Logar', class: "btn-default" %>
  </div>
  <% end %>	
</div>